# Generated by Django 2.1.2 on 2018-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Instrument',
            field=models.CharField(choices=[('G', 'Guitar'), ('P', 'Piano'), ('B', 'Base'), ('D', 'Drum')], max_length=1, null=True),
        ),
    ]
