# Generated by Django 2.1.2 on 2018-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_user_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='1234567890', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='Instrument',
            field=models.CharField(blank=True, choices=[('G', 'Guitar'), ('P', 'Piano'), ('B', 'Base'), ('D', 'Drum'), ('V', 'Vocal')], max_length=1, null=True),
        ),
    ]
