# Generated by Django 2.1.2 on 2018-11-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_auto_20181113_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
