# Generated by Django 2.1.2 on 2018-11-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_auto_20181113_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Instrument',
            new_name='Instrument_1',
        ),
        migrations.AddField(
            model_name='user',
            name='Commitee_member',
            field=models.CharField(blank=True, choices=[('ED', 'Education'), ('EV', 'Event'), ('FI', 'Finanace'), ('PE', 'Performance'), ('PR', 'Propaganda'), ('PU', 'Publicity'), ('SE', 'Secretary')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Instrument_2',
            field=models.CharField(blank=True, choices=[('G', 'Guitar'), ('P', 'Piano'), ('B', 'Base'), ('D', 'Drum'), ('V', 'Vocal')], max_length=1, null=True),
        ),
    ]
