# Generated by Django 2.1.2 on 2018-11-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0006_auto_20181113_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Commitee_member',
            new_name='Committee_member',
        ),
    ]
